### ISSUE TITLE
Unexpected inspection reports for exported variables

### ISSUE THREAD

**Issue by NickSdot** [BashSupport-Pro/bashsupport-pro#108]
First things first: Thanks for this great tool. I am testing it for a few days now and it improved my DX with Bash a ton. 🚀 

However, a few things somehow not really add up. One of it I would like to report with a very simplified example below. Thanks in advance for having a look!

# Bash Support Pro Active

### dir/scripts/first_executable_command
```bash
#!/usr/bin/env bash

main() {
  local argument=""
  local command_arguments=()

  export __md_debug_active=0

  while (( ${#} )); do

    argument="${1:-}" && shift

    case "${argument}" in
      --debug)
        export __md_debug_active=1
        ;;
      *) command_arguments+=("${argument}") ;;
    esac

  done

  # export __md_debug_active <-- also tried to above declare only and export here; same result 

  # if/else executing subcommands here
  dir/scripts/second_executable_command "${command_arguments[@]"
}

main "$@"
```

### dir/scripts/second_executable_command
```bash
#!/usr/bin/env bash

main() {
  printf "%s" "${__md_debug_active:-0}" # correctly prints 0/1 depending on option flag in parent
}

main "$@"
``` 

**Actual behavior:**
1. In `dir/scripts/first_executable_command`. No matter an export is used in front of each `__md_debug_active` or after declaration, it has the inspection message 'Variable could be local'.
2. In `dir/scripts/second_executable_command` I get the inspection message '__md_debug_active is referenced but not assigned'.

**Expected behavior:**
No inspection problems reported.

**Additional info:**
- Problem appears in IntelliJ IDEA with Bash Support Pro; both in the latest version available
- Google code style activated
- Restarted IntelliJ caches and restartet
- Tried renaming variables in various ways (__md_debug_active, md_debug_active, _md_debug_active
- Tried all above naming variants in all caps, but then I get 'Variable names must be lowercase' (this somehow isn't the case for init files without a main function)
- 
<img width="711" alt="image" src="https://user-images.githubusercontent.com/32384907/168409325-5a15808c-c772-44fb-8011-cb86ccb4a51c.png">

# No Bash Support Pro
If I disable Bash Support Pro all together and go back to Jetbrains default with Shellcheck, no inspection problems are reported by using the example from above.

**Comment by NickSdot** [comment]
Apart from the actual problem I would like to add that it would be awesome to have a more easy way to suppress inspection reports.

The current way in BashSupport Pro  is:
1. Click on the reported error
2. Click Options + Enter
3. Click Arrow Right 
4. Navigate down

<img width="740" alt="image" src="https://user-images.githubusercontent.com/32384907/168410148-325493de-dfa7-4412-818c-4a23fa1d5adc.png">

With Shellcheck that's imho more smooth by just using the quick suppress feature in the tooltip.

**Comment by jansorg** [comment]
@NickSdot Thank you for your detailed report!

## First file 
`export` used inside a function sets the export flag on a variable. If it wasn't declared yet, then it's declared as a global variable. That's why the message `Variable could be local` shows up.
You could fix it like this:
```bash
main() {
  local argument=""
  local command_arguments=()

  declare __md_debug_active # declares the variables as a local variable
  export __md_debug_active=0

  # or just like this in one step, declare makes it a local variable and "-x" sets the export flag
  declare -x __md_debug_active=0
  # ...
}
```

"variable could be local" is currently a warning. Was that warning irritating to you? Would you have prefered a less strong info message instead?

I'm planning to add a quickfix on the warning "variable could be local" to make it easier to fix. Hopefully that'll help and make it less of a concern to users.

## Second file
I'm currently not sure why you're seeing "_md_debug_active is referenced but not assigned". This should only be shown without the `:-0` part in the parameter expansion.
`${__md_debug_active:-0}` should have no warning, but `${__md_debug_active}` should show it. 
Can you confirm that the warning is displayed for `${__md_debug_active:-0}` in your editor?

Do you have inspection "Unresolved variable" enabled?
![image](https://user-images.githubusercontent.com/11473063/168418433-b33f99af-65a9-4992-a060-7db84a51186f.png)

The variable is defined at runtime, because you're first exporting the variable and then executing the 2nd script. It's not possible to reliably detect this because it's runtime information. BashSupport Pro is only supporting sourced files to locate variable declarations, but not scripts executed as commands. 

You already used the `:-0}` fallback, which is a good solution for such a case. Another way to fix it is to declare it as a project variable using the provided quickfix, but that's most likely too much because it applies to all scripts. You could also add a `# shellcheck disable=SC2154` line above it to suppress the warning.

**Comment by jansorg** [comment]
Regarding suppressing warnings: BashSupport Pro tries to follow the common pattern to show the options to suppress a warning in the sub menu. That's how Java and other languages are doing it. 
Are you usually suppressing warnings in other languages or mostly only in Bash? If that's the case, do you know why that might happen?

JetBrains Shell takes a different approach, as you noticed. It's quite useful for a single warning, but could grow large when there's more than one.
![Screenshot_20220514_105348](https://user-images.githubusercontent.com/11473063/168418716-ab877529-e5af-4e32-8632-e951024adf75.png)

**Comment by NickSdot** [comment]
Thanks for your answer!

> export used inside a function sets the export flag on a variable. If it wasn't declared yet, then it's declared as a global variable. That's why the message Variable could be local shows up.

Well, I was confused why BSP would report it, while the standard setup does not. That said and thinking it further,I can live with this workaround. Thanks.

> Can you confirm that the warning is displayed for `${__md_debug_active:-0}` in your editor?

I can't. With `:-` indeed is also in BSP everything alright. I must have missed that switching back and forth while debugging. So everything alright and basically a false report from me. Sorry for wasting your time  – my bad, sorry!

**Comment by NickSdot** [comment]
> Regarding suppressing warnings: BashSupport Pro tries to follow the common pattern to show the options to suppress a warning in the sub menu. That's how Java and other languages are doing it. 


I didn't mean that you remove the submenu navigation. It would just be comfortable to have a more quick way to suppress a warning in beside of the quick fix too. 

> Are you usually suppressing warnings in other languages or mostly only in Bash? If that's the case, do you know why that might happen?

Not often, but it happens. A good example would be using Bash's $REPLY var. The code-style inspection expects lower-case var names. The quick fix offered is to change to lower-case. I would find it useful to have a second quick option to disable the warning for the statement.

---

Allow me a quick other question without opening a new issue. Is re-factoring file names managed by BSP too?

**Comment by jansorg** [comment]
> Not often, but it happens. A good example would be using Bash's $REPLY var. The code-style inspection expects lower-case var names. The quick fix offered is to change to lower-case. I would find it useful to have a second quick option to disable the warning for the statement.

Thanks, I'll think about it.
But this particular issues seems more like a bug with the inspection. I'll see what I can do to fix it.
 
> Allow me a quick other question without opening a new issue. Is re-factoring file names managed by BSP too?

Yes, for sourced file paths and `# shellcheck source=` directives. It's currently not (yet) handling file references in command executions.

https://www.bashsupport.com/manual/editor/move-file/
https://www.bashsupport.com/manual/editor/shellcheck/#shellcheck-directives
