### ISSUE TITLE
Can not open .sh file in any way after unistall

### ISSUE THREAD

**Issue by LeetJoe** [BashSupport-Pro/bashsupport-pro#133]
Well, though I have not paid for this and just tried, while after I uninstalled the plugin, I just can not open my .sh file again in PyCharm. And the .sh file I never opened by the plugin not affected by this.
Then I reinstalled the plugin and the file could be opened again, and i disabled the plugin instead uninstalling it. After restarting PyCharm, I can not open my .sh files again.
So I can not open my .sh file after I tried this plugin, right?

**Comment by LeetJoe** [comment]
Fixed by setting the Settings -> Editor -> File Type and set the .sh associate with shell script. Myabe it was reset by the plugin and did not change it back after installed?

**Comment by jansorg** [comment]
I'm glad you found the fix.
The cause is located in the IDE platform, I reported this last year to JetBrains at https://youtrack.jetbrains.com/issue/IDEA-297533/File-type-association-not-restored-after-uninstalling-a-plugin
Adding a workaround to restore the file associations when uninstalling BashSupport Pro is difficult (if even possible), but I'll see what I can do.
