### ISSUE TITLE
Quote subshell to prevent word splitting?

### ISSUE THREAD

**Issue by forestplay** [BashSupport-Pro/bashsupport-pro#30]
This line is marked with "Quote this to prevent word splitting"

  echo "##### Starting "$(basename "$0")

I don't know what to quote here.  Is this a bashsupport-pro issue?

**Comment by jansorg** [comment]
The ShellCheck integration of BashSupport Pro is displaying this message.

If you move the closing quote to the end of the line, then the message will disappear. 
This removes the warnings:
```
echo "##### Starting $(basename "$0")"
```

or 
```
# shellcheck disable=SC2046
echo "##### Starting "$(basename "$0")
```

It's shown, because `$(basename "$0")` may output multiple words separated by whitespace and Bash would split this up into multiple arguments unless it's quoted. It doesn't make a lot of sense for "echo", but commands like `cd` are sensitive to whitespace and quoting should be used, as suggested by ShellCheck.

**Comment by forestplay** [comment]
Rewriting line as

  echo "##### Starting $(basename "$0")"

works as expected and removes warning/errors.  Thanks!

**Comment by jansorg** [comment]
Thanks for confirming!
