### ISSUE TITLE
bats-core - setup_file and teardown_file are not executed

### ISSUE THREAD

**Issue by Compile-Time** [BashSupport-Pro/bashsupport-pro#48]
When running a single bats test in IntelliJ, the setup_file and teardown_file functions are not executed.
I verified this with the following sample.
```sh
#!/usr/bin/env bats

setup_file() {
  echo '# run setup_file' >&3
}

setup() {
  echo '# run setup' >&3
}

teardown() {
  echo '# run teardown' >&3
}

teardown_file() {
  echo '# run teardown_file' >&3
}

@test "setup_file and teardown_file not executed" {
  echo '# run test' >&3
  [[ 1 -eq 1 ]]
}
```
In IntelliJ only the echo's from setup() and teardown() are shown.
![image](https://user-images.githubusercontent.com/18414241/93722538-dcb98280-fb97-11ea-9005-969a723b3b77.png)

When I run the same file directly in a terminal, I also see the output of teardown_file and setup_file.
![image](https://user-images.githubusercontent.com/18414241/93722466-4f762e00-fb97-11ea-974e-b3c0dd3206ac.png)
(I don't know why the output is a bit broken here but it should be irrelevant to the actual issue.)

Using IntelliJ IDEA 2020.2.2 (Ultimate Edition)
Build #IU-202.7319.50
Plugin Version: 1.4.14.202

**Comment by jansorg** [comment]
@Compile-Time Thanks for reporting!
`setup_file` and `teardown_file` were added with [1.2.1](https://github.com/bats-core/bats-core/compare/v1.2.0...v1.2.1). Version 1.4 of BashSupport Pro bundles 1.2.0 of bats-core, which explains which this feature is not yet available. Using the installed version isn't possible (yet), because minor modifications were needed to integrate the output with the requirements of the IntelliJ test runners.

I've updated bats-core 1.2.1 for the next update 1.5.x ([eap here](https://plugins.jetbrains.com/plugin/13841-bashsupport-pro/versions/eap/97250)) and expect to ship a public update later this week.
