### ISSUE TITLE
Conflicting recommendations ... clarification requested.

### ISSUE THREAD

**Issue by arvidj01** [BashSupport-Pro/bashsupport-pro#55]
The "What's new" suggests:

Fixed

        Performance optimization: code completion in script files now appears faster.
        Shell files without extensions are now properly assigned to BashSupport Pro if **JetBrains Shell is enabled**.
        Language injection into Makefiles is now properly working when **JetBrains Shell is enabled**.

But when IntelliJ restarts with the JetBrains Shell enabled the following warning is issued:

BashSupport Pro is a standalone plugin now-it doesn't require the JetBrains Shell anymore. The features didn't change, of course. Shell's run configurations are supported by BashSupport Pro. **It's strongly recommended to disable the Shell plugin.**

Just wondering if it should be enabled to take advantage of the two fixes listed or if is should not be enabled ... which then makes one wonder about the two fixes.

Clarification requested. Thanks.

**Comment by jansorg** [comment]
@arvidj01 BashSupport Pro is doing everything the JetBrains Shell plugin does plus a lot more. There's shouldn't be any need for the Shell plugin (let me know if there is). 
Running BashSupport + Pro is still problematic, even with the fixes above, e.g. run configuration support is still a potential source of errors.

The fixes of 1.5.10 are for two kinds of setups:
- The notification does not appear on CLion, because CLion's Makefile support requires the Shell plugin for its Makefile support. BashSupport Pro will show the notification on CLion again, when the Makefile support isn't requiring the Shell plugin anymore. I don't know if that'll happen for 2020.3 or later, if ever. The new fixes allow to support Shell scripting on CLion as good as possible.
- For users, which decided to keep the Shell plugin enabled - the notification will not show up after dismissing it a few times. I'm not sure why users would do this, but it's still their choice, of course.

Does this sufficiently answer your question?

**Comment by arvidj01** [comment]
Thanks. That defines what needs to be done. It was the "if "JetBrains Shell is enabled" in the update notes that caused the confusion. Seemed to imply that was the only way the Shell files without and extension would work.

Anyway, turned Shell off.

**Comment by jansorg** [comment]
I see what you mean, I'll try to make this point clearer in the future.
